language: python
sudo: required
# if the https://travis-ci.org/ODM2/ODM2PythonAPI/requests ever says: missing config
# validate at: http://lint.travis-ci.org/
python:
#  - "2.6"
  - "2.7"
#  - "3.2"
#  - "3.3"
#  - "3.4"
#  - "3.5"
#  - "3.5-dev" # 3.5 development branch
#  - "nightly" # currently points to 3.6-dev
# command to install dependencies
cache:
  directories:
    - $HOME/.cache/pip/wheels
    - $HOME/virtualenv/python2.7.9
addons:
  apt:
    packages:
      - python-lxml
#services:
 # - mysql
#  - postgresql
before_script:
  - python examples/flask/cbi/build_cbi_cache.py
  - python examples/flask/swis/runserver_swis.py --config=./test/test_swis_config2.cfg --connection=sqlite:///./test/test_swis2.db &

before_install:
# python -m pip makes the install go into the virtualenv
  - python -m pip install pysqlite sqlalchemy requests suds lxml
install: # now just our code
  - pip install   .
#  - pip install pysqlite sqlalchemy requests suds
  - pip list

# don't forget to open up the azure mssql server to these addreses
# https://docs.travis-ci.com/user/ip-addresses/

# command to run tests
script:
 # - nosetests --verbosity=1 -w test
  - py.test test